// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  appointments: dynamic(() => import("./Appointments")),
  bento: dynamic(() => import("./Bento")),
  booking: dynamic(() => import("./Calendar")),
  call_to_action: dynamic(() => import("./CallToAction")),
  case_study: dynamic(() => import("./CaseStudy")),
  hero: dynamic(() => import("./Hero")),
  integrations: dynamic(() => import("./Integrations")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
};
